package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

var templateFuncs = template.FuncMap{
	"dict":    dict,
	"list":    list,
	"targets": targets,
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: gen-templates <sub-package-path> <target-file-name>")
	os.Exit(2)
}

func main() {
	if len(os.Args) != 3 {
		usage()
	}

	subPackagePath := os.Args[1]
	targetFileName := os.Args[2]

	templatesDir := filepath.Join(subPackagePath, "templates")
	templateFiles, err := findTemplateFiles(templatesDir)
	if err != nil {
		fail("list templates", err)
	}
	if len(templateFiles) == 0 {
		fail("list templates", fmt.Errorf("no .tmpl files found in %s", templatesDir))
	}

	data := map[string]any{}
	var rendered bytes.Buffer

	rendered.WriteString("// Code generated by gen-templates; DO NOT EDIT.\n\n")

	for _, templateFile := range templateFiles {
		src, err := os.ReadFile(templateFile)
		if err != nil {
			fail("read template", err)
		}

		tmpl, err := template.New(filepath.Base(templateFile)).Funcs(templateFuncs).Parse(string(src))
		if err != nil {
			fail("parse template", err)
		}

		rendered.WriteString(fmt.Sprintf("/* === %s === */\n\n", templateFile))

		if err := tmpl.Execute(&rendered, data); err != nil {
			fail("render template", err)
		}
		if rendered.Len() > 0 && !bytes.HasSuffix(rendered.Bytes(), []byte("\n")) {
			rendered.WriteByte('\n')
		}
		rendered.WriteByte('\n')
	}

	formatted, err1 := format.Source(rendered.Bytes())
	if err1 != nil {
		formatted = rendered.Bytes()
	}

	targetPath := filepath.Join(subPackagePath, targetFileName)
	if err2 := os.WriteFile(targetPath, formatted, 0644); err2 != nil {
		fail("write generated source", err2)
	}

	if err1 != nil {
		fail("format generated source", err1)
	}
}

func findTemplateFiles(templatesDir string) ([]string, error) {
	entries, err := os.ReadDir(templatesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("templates directory not found: %s", templatesDir)
		}
		return nil, err
	}

	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if strings.HasSuffix(entry.Name(), ".tmpl") {
			files = append(files, filepath.Join(templatesDir, entry.Name()))
		}
	}
	sort.Strings(files)
	return files, nil
}

func dict(vals ...any) (map[string]any, error) {
	if len(vals)%2 != 0 {
		return nil, fmt.Errorf("dict expects key/value pairs")
	}

	m := make(map[string]any, len(vals)/2)
	for i := 0; i < len(vals); i += 2 {
		k, ok := vals[i].(string)
		if !ok {
			return nil, fmt.Errorf("dict keys must be strings")
		}
		m[k] = vals[i+1]
	}
	return m, nil
}

func list(vals ...any) []any {
	return vals
}

func targets(src string) ([]map[string]any, error) {
	chunks := strings.Split(src, "\n\n")
	items := make([]map[string]any, 0, len(chunks))
	for _, chunk := range chunks {
		chunk = strings.TrimSpace(chunk)
		if chunk == "" {
			continue
		}

		item := make(map[string]any)
		for lineNo, line := range strings.Split(chunk, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}

			sep := strings.IndexAny(line, ":=")
			if sep < 0 {
				return nil, fmt.Errorf("invalid target line %q: expected ':' or '='", line)
			}

			key := strings.TrimSpace(line[:sep])
			value := strings.TrimSpace(line[sep+1:])
			if key == "" {
				return nil, fmt.Errorf("invalid target line %d in block %q: empty key", lineNo+1, chunk)
			}
			parsed, err := parseTargetValue(value)
			if err != nil {
				return nil, fmt.Errorf("invalid value for %s: %w", key, err)
			}
			item[key] = parsed
		}

		if len(item) > 0 {
			items = append(items, item)
		}
	}
	return items, nil
}

func parseTargetValue(raw string) (any, error) {
	if raw == "" {
		return "", nil
	}

	if len(raw) >= 2 {
		if unquoted, err := strconv.Unquote(raw); err == nil {
			return unquoted, nil
		}
	}

	if raw == "true" {
		return true, nil
	}
	if raw == "false" {
		return false, nil
	}
	if i, err := strconv.ParseInt(raw, 10, 64); err == nil {
		return i, nil
	}
	if f, err := strconv.ParseFloat(raw, 64); err == nil {
		return f, nil
	}

	return raw, nil
}

func fail(action string, err error) {
	_, _ = fmt.Fprintf(os.Stderr, "gen-templates: %s: %v\n", action, err)
	os.Exit(1)
}
